const toDate = require('../../helpers/to-date');
const createdAt = new Date();

const events = [
  {
    name: 'Test Event 1',
    content: 'This is a description for test event 1',
    startAt: toDate('2022-12-01'),
    createdAt,
    userId: 1,
    calendarId: 1,
    type: 'arrangement',
  },
  {
    name: 'Test Event 2',
    content: 'This is a description for test event 2',
    startAt: toDate('2022-12-01'),
    createdAt,
    userId: 1,
    calendarId: 1,
    type: 'arrangement',
  },
  {
    name: 'Test Event 3',
    content: 'This is a description for test event 3',
    startAt: toDate('2022-12-01'),
    createdAt,
    userId: 1,
    calendarId: 1,
    type: 'arrangement',
  },
  {
    name: 'Test Event 2',
    content: 'This is a description for test event 1',
    startAt: toDate('2022-12-03'),
    createdAt,
    userId: 2,
    calendarId: 2,
    type: 'arrangement',
  },
  {
    name: 'Test Event 2',
    content: 'This is a description for test event 1',
    startAt: toDate('2022-12-03'),
    createdAt,
    userId: 2,
    calendarId: 2,
    type: 'arrangement',
  },
  {
    name: 'Test Event 2',
    content: 'This is a description for test event 1',
    startAt: toDate('2022-12-03'),
    createdAt,
    userId: 2,
    calendarId: 2,
    type: 'arrangement',
  },
  {
    name: 'Test Event 3',
    content: 'This is a description for test event 3',
    startAt: toDate('2022-12-05'),
    createdAt,
    userId: 3,
    calendarId: 3,
    type: 'arrangement',
  },
  {
    name: 'Test Event 3',
    content: 'This is a description for test event 3',
    startAt: toDate('2022-12-05'),
    createdAt,
    userId: 3,
    calendarId: 3,
    type: 'arrangement',
  },
  {
    name: 'Test Event 3',
    content: 'This is a description for test event 3',
    startAt: toDate('2022-12-05'),
    createdAt,
    userId: 3,
    calendarId: 3,
    type: 'arrangement',
  },
  {
    name: 'Test Event 4',
    content: 'This is a description for test event 4',
    startAt: toDate('2022-12-07'),
    createdAt,
    userId: 4,
    calendarId: 4,
    type: 'arrangement',
  },
  {
    name: 'Test Event 4',
    content: 'This is a description for test event 4',
    startAt: toDate('2022-12-07'),
    createdAt,
    userId: 4,
    calendarId: 4,
    type: 'arrangement',
  },
  {
    name: 'Test Event 4',
    content: 'This is a description for test event 4',
    startAt: toDate('2022-12-07'),
    createdAt,
    userId: 4,
    calendarId: 4,
    type: 'arrangement',
  },
  {
    name: 'Test Event 5',
    content: 'This is a description for test event 5',
    startAt: toDate('2022-12-10'),
    createdAt,
    userId: 5,
    calendarId: 5,
    type: 'arrangement',
  },
  {
    name: 'Test Event 5',
    content: 'This is a description for test event 5',
    startAt: toDate('2022-12-10'),
    createdAt,
    userId: 5,
    calendarId: 5,
    type: 'arrangement',
  },
  {
    name: 'Test Event 5',
    content: 'This is a description for test event 5',
    startAt: toDate('2022-12-10'),
    createdAt,
    userId: 5,
    calendarId: 5,
    type: 'arrangement',
  },
];

module.exports = events;
